DROP TABLE IF EXISTS "document" CASCADE;

DROP TABLE IF EXISTS "transactions" CASCADE;

DROP TABLE IF EXISTS "account" CASCADE;

DROP TABLE IF EXISTS "user_info" CASCADE;

DROP TABLE IF EXISTS "userGroupings" CASCADE;

DROP TABLE IF EXISTS "userMethods" CASCADE;

DROP TABLE IF EXISTS "transactionGroups" CASCADE;

DROP TABLE IF EXISTS "transactionMethods" CASCADE;
