CREATE TABLE IF NOT EXISTS "document" (
	"created" TIMESTAMP NOT NULL,
	"modified" TIMESTAMP NOT NULL,
	"modified_by" VARCHAR(65) NOT NULL
);




CREATE TABLE IF NOT EXISTS "transactions" (
	"id" VARCHAR(65) NOT NULL UNIQUE,
	"description" TEXT,
	"transaction_time" TIMESTAMP NOT NULL,
	"accountID" VARCHAR(65) NOT NULL,
	"amount" MONEY NOT NULL,
	"type" BOOLEAN NOT NULL,
	"method" VARCHAR(65) NOT NULL,
	PRIMARY KEY("id")
) INHERITS ("document");




CREATE TABLE IF NOT EXISTS "account" (
	"id" VARCHAR(65) NOT NULL UNIQUE,
	"email" VARCHAR(50) NOT NULL,
	"password" VARCHAR(65) NOT NULL,
	"fname" VARCHAR(50) NOT NULL,
	"lname" VARCHAR(50) NOT NULL,
	"mname" VARCHAR(50),
	PRIMARY KEY("id")
) INHERITS ("document");




CREATE TABLE IF NOT EXISTS "user_info" (
	"id" VARCHAR(65) NOT NULL UNIQUE,
	"fname" VARCHAR(50) NOT NULL,
	"lname" VARCHAR(50) NOT NULL,
	"mname" VARCHAR(50),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "userGroupings" (
	"id" VARCHAR(65) NOT NULL UNIQUE,
	"name" VARCHAR(50) NOT NULL,
	"accountID" VARCHAR(65) NOT NULL,
	"parent" VARCHAR(65),
	PRIMARY KEY("id")
) INHERITS ("document");




CREATE TABLE IF NOT EXISTS "userMethods" (
	"id" VARCHAR(65) NOT NULL UNIQUE,
	"name" VARCHAR(50) NOT NULL,
	"accountID" VARCHAR(65) NOT NULL,
	PRIMARY KEY("id")
) INHERITS ("document");




CREATE TABLE IF NOT EXISTS "transactionGroups" (
	"transactionID" VARCHAR(65) NOT NULL ,
	"groupID" VARCHAR(65) NOT NULL 
) INHERITS ("document");



ALTER TABLE "document"
ADD FOREIGN KEY("modified_by") REFERENCES "account"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "transactions"
ADD FOREIGN KEY("accountID") REFERENCES "account"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "userGroupings"
ADD FOREIGN KEY("accountID") REFERENCES "account"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "userGroupings"
ADD FOREIGN KEY("parent") REFERENCES "userGroupings"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "userMethods"
ADD FOREIGN KEY("accountID") REFERENCES "account"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "transactionGroups"
ADD FOREIGN KEY("groupID") REFERENCES "userGroupings"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "transactionGroups"
ADD FOREIGN KEY("transactionID") REFERENCES "transactions"("id")
ADD CONSTRAINT UQ_gID_tID UNIQUE ("groupID", "transactionID")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "transactions"
ADD FOREIGN KEY("method") REFERENCES "userMethods"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;